#!/usr/bin/env python3

import unicodedata
import fnmatch
import sys
import os

if len(sys.argv) < 2:
	print("Normalize files to Unicode NFKC. Specify names of files in the current directory - wildcards are supported.")

for file in os.listdir('.'):
	for arg in sys.argv:
		if fnmatch.fnmatch(file, arg):
			inf = file + '.bak'
			os.rename(file, inf)
			with open(inf) as inf:
				with open(file,'w+') as outf:
					for line in inf:
						outf.write(unicodedata.normalize("NFKC", line))
